server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = /release-center {
    return 301 /release-center/;
  }

  location /release-center/assets/ {
    root /usr/share/nginx/html;
  }

  location /release-center/ {
    try_files $uri $uri/ /release-center/index.html;
  }
}
